name: doj_tv
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.5
  lecle_yoyo_player: ^0.0.8
  sizer: ^2.0.15
  cloud_firestore: ^4.12.1
  firebase_core: ^2.20.0
  firebase_auth: ^4.12.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dojtv_1.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#101010"
  image: assets/images/doj_tv.png

  android_12:
    image: assets/images/doj_tv.png
    icon_background_color: "#101010"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/videos/
